### ISSUE TITLE
TS3AudioBot "Permission Denied" at intial start

### ISSUE THREAD

**Issue by CookieCr2nk** [CookieCr2nk/TS3AudioBot-Docker#5]
Ts3AudioBot couldn't started to initialize the TS3AudioBot directory. 

x@x:/opt/docker-data$ docker run --rm -v /opt/docker-data/ts3audiobot:/data -it ghcr.io/cookiecr2nk/ts3audiobot-docker:master
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/data/NLog.config' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileInfo.OpenWrite()
   at TS3AudioBot.Setup.SetupLog() in C:\projects\ts3audiobot\TS3AudioBot\Setup.cs:line 103
   at TS3AudioBot.Setup.Main(String[] args) in C:\projects\ts3audiobot\TS3AudioBot\Setup.cs:line 73
x@x:/opt/docker-data$

**Comment by CookieCr2nk** [comment]
Issue solved, permission wasn't set right.
